---
- hosts: all
  vars:
    php_enablerepo: "remi,remi-php70"
    php_enable_webserver: false
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
  tasks:
    - name: Install Packages
      apt: name= state=latest update_cache=yes
      with_items:
        - ntp
        - python
        - tcpdump
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - wget
        - openssl
        - curl
        - vim
    - name: install lamp stack
      become: yes
      become_user: root
      apt:
        pkg:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-xml
          - php-gd
          - php-curl
          - libapache2-mod-php
          - php-cli
          - php-mbstring
          - php-zip
        state: present
        update_cache: yes

    - name: start apache service
      become: yes
      become_user: root
      service:
        name: apache2
        state: started
        enabled: yes

    - name: start mysql service
      become: yes
      become_user: root
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create target directory
      file: path=/var/www/dev state=directory mode=0755

    - git:
      repo: 'https://github.com/drupal/drupal.git'
      dest: /tmp/drupal-app
      version: release-8.6

    - name: deploy drupal
      become: yes
      become_user: root
      copy:
        src: /tmp/drupal-app
        dest: /var/www/dev/drupal-app
