---
- hosts: all
  vars_files:
      - "vars.yml"
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
  tasks:
    - name: Install Packages
      apt: name= state=latest update_cache=yes
      with_items:
        - ntp
        - python
        - tcpdump
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - wget
        - openssl
        - curl
        - vim
    - name: install lamp stack
      become: yes
      become_user: root
      apt:
        pkg:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-xml
          - php-gd
          - php-curl
          - libapache2-mod-php
          - php-cli
          - php-mbstring
          - php-zip
        state: present
        update_cache: yes
    - name: Set date.timezone for PHP CLI
      become: true
      lineinfile:
        dest: /etc/php/7.2/apache2/php.ini
        regexp: "date.timezone ="
        line: "date.timezone = UTC"
    - name: Increase scripts max_execution_time
      become: true
      lineinfile:
        dest: /etc/php/7.2/apache2/php.ini
        regexp: "max_execution_time = 30"
        line: "max_execution_time = 50"
    - name: Increase max_input_time
      become: true
      lineinfile:
        dest: /etc/php/7.2/apache2/php.ini
        regexp: "max_input_time = 60"
        line: "max_input_time = 60"
    - name: Set higher memory_limit
      become: true
      lineinfile:
        dest: /etc/php/7.2/apache2/php.ini
        regexp: "memory_limit = 128M"
        line: "memory_limit = 512M"
    - name: Set display_errors to On on dev server
      become: true
      lineinfile:
        dest: /etc/php/7.2/apache2/php.ini
        regexp: "display_errors = Off"
        line: "display_errors = On"
    - name: Increase upload_max_filesize for videos
      become: true
      lineinfile:
        dest: /etc/php/7.2/apache2/php.ini
        regexp: "upload_max_filesize = 2M"
        line: "upload_max_filesize = 20M"

    - name: start apache service
      become: yes
      become_user: root
      service:
        name: apache2
        state: started
        enabled: yes

    - name: start mysql service
      become: yes
      become_user: root
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create target directory
      file: path=/var/www/dev state=directory mode=0755

    - git:
      repo: 'https://github.com/drupal/drupal.git'
      dest: /tmp/drupal-app
      version: HEAD

    - name: deploy drupal
      become: yes
      become_user: root
      copy:
        src: /tmp/drupal-app
        dest: /var/www/dev/drupal-app
