    - name: Set settings for PHP
      become: true
      ini_file:
        dest: /etc/php/7.0/fpm/php.ini
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: Date, option: date.timezone, value: Europe/Berlin }
        - { section: PHP, option: max_execution_time, value: 60 }
        - { section: PHP, option: memory_limit, value: 512M }
